-- Добавление колонок для профиля игрока
ALTER TABLE t_p89978113_website_creation_pro.users
ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS exp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gems INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS play_time_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS avatar TEXT,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS kills INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS deaths INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS quests INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS achievements INTEGER DEFAULT 0;